Fix the clap syntax for long options.
In the recently updated version of clap, long options don't expect the "--"
to be included in the string.

This fixes errors with any use of the CLI:
```
$ cargo run -- keygen --public-key=public.key --secret-key=secret.key
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/wasmsign2 keygen --public-key=p --secret-key=s`

thread 'main' (461924) panicked at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.53/src/builder/debug_asserts.rs:76:13:
Argument secret_key: long "--secret-key" must not start with a `-`, that will be handled by the parser
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```